export const SET_LOADING = 'SET_LOADING';
export const GET_INVENTORY = 'GET_INVENTORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_SPORTS = 'GET_SPORTS';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const GET_USERS = 'GET_USERS';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const GET_PRODUCT_ID = 'GET_PRODUCT_ID';
export const FILTER_PRODUCTS_BY_NAME = 'FILTER_PRODUCTS_BY_NAME';
export const RESET_DISPLAYED_PRODUCTS = 'RESET_DISPLAYED_PRODUCTS';
export const ORDER_PRODUCTS_BY_PRICE = 'ORDER_PRODUCTS_BY_PRICE';
export const FILTER_PRODUCTS_BY_STATUS = 'FILTER_PRODUCTS_BY_STATUS';
export const FILTER_USERS_BY_ROLE_AND_STATUS = 'FILTER_USERS_BY_ROLE_AND_STATUS';

